import { ITrack } from "../models/models";

export const musicListInitState: ITrack[] = [
  {
    name: "The Diary Of Jane",
    singer: "Breaking_Benjamin",
    genre: "Rock",
    audio: "./music/Breaking_Benjamin-The_Diary_Of_Jane.mp3",
    album_img: "./images/diary_of_jane_cover.jpg",
    id: 1,
  },
  {
    name: "Throne",
    singer: "Bring Me The Horizon",
    genre: "Rock",
    audio: "./music/Bring_Me_The_Horizon–Throne.mp3",
    album_img: "./images/thats_the_spirit_cover.jpg",
    id: 2,
  },
  {
    name: "Safe And Sound",
    singer: "Capital Cities",
    genre: "Pop",
    audio: "./music/Capital_Cities-Safe_And_Sound.mp3",
    album_img: "./images/safe_and_sound.jpg",
    id: 3,
  },
  {
    name: "Stay With Me",
    singer: "Celldweller",
    genre: "Rock",
    audio: "./music/Celldweller-Stay_with_me.mp3",
    album_img: "./images/stay_with_me_cover.jpg",
    id: 4,
  },
  {
    name: "Bury It",
    singer: "CHVRCHES",
    genre: "Pop",
    audio: "./music/CHVRCHES-Bury_It.mp3",
    album_img: "./images/bury_it_cover.jpg",
    id: 5,
  },
  {
    name: "Paradise",
    singer: "Coldplay",
    genre: "Pop",
    audio: "./music/Coldplay-Paradise.mp3",
    album_img: "./images/paradise_cover.jpg",
    id: 6,
  },
  {
    name: "End of Line",
    singer: "Daft Punk",
    genre: "Electronic",
    audio: "./music/Daft_Punk–End_of_Line.mp3",
    album_img: "./images/end_of_line_cover.jpg",
    id: 7,
  },
  {
    name: "From Nowhere",
    singer: "Dan Croll",
    genre: "Electronic",
    audio: "./music/Dan_Croll-From_Nowhere_(Baardsen_Remix).mp3",
    album_img: "./images/from_nowhere_cover.jpg",
    id: 8,
  },
  {
    name: "Mockingbird",
    singer: "Eminem",
    genre: "Rap",
    audio: "./music/Eminem–Mockingbird.mp3",
    album_img: "./images/mockingbird_cover.jpg",
    id: 9,
  },
  {
    name: "The Greatest View",
    singer: "Flume",
    genre: "Pop",
    audio: "./music/Flume-The_Greatest_View.mp3",
    album_img: "./images/the_greatest-view_cover.jpg",
    id: 10,
  },
  {
    name: "High Road",
    singer: "Fort Minor",
    genre: "Rap",
    audio: "./music/Fort_Minor-High_road.mp3",
    album_img: "./images/high_road_cover.jpg",
    id: 11,
  },
  {
    name: "My Life Be Like",
    singer: "Grits",
    genre: "Rap",
    audio: "./music/Grits-My_Life_Be_Like.mp3",
    album_img: "./images/my_life_be_like.jpg",
    id: 12,
  },
  {
    name: "Demons",
    singer: "Imagine Dragons",
    genre: "Pop",
    audio: "./music/Imagine_Dragons–Demons.mp3",
    album_img: "./images/demons_cover.jpg",
    id: 13,
  },
  {
    name: "In the End",
    singer: "Linkin Park",
    genre: "Rock",
    audio: "./music/Linkin_Park–In_the_End.mp3",
    album_img: "./images/in_the_end_cover.jpg",
    id: 14,
  },
  {
    name: "Midnight City",
    singer: "M83",
    genre: "Electronic",
    audio: "./music/M83-Midnight_City.mp3",
    album_img: "./images/midnight_city_cover.jpg",
    id: 15,
  },
  {
    name: "Dont Call Me Up",
    singer: "Mabel",
    genre: "Pop",
    audio: "./music/Mabel–Dont_Call_Me_Up.mp3",
    album_img: "./images/dont_call_me_up_cover.jpg",
    id: 16,
  },
  {
    name: "Counting Stars",
    singer: "OneRepublic",
    genre: "Pop",
    audio: "./music/OneRepublic-Counting_Stars.mp3",
    album_img: "./images/counting_stars_cover.jpg",
    id: 17,
  },
  {
    name: "Где нас нет",
    singer: "Oxxymiron",
    genre: "Rap",
    audio: "./music/Oxxymiron–Где_нас_нет.mp3",
    album_img: "./images/gde_nas_net_cover.jpg",
    id: 18,
  },
  {
    name: "Witchcraft",
    singer: "Pendulum",
    genre: "Rock",
    audio: "./music/Pendulum-Witchcraft.mp3",
    album_img: "./images/witchcraft_cover.jpg",
    id: 19,
  },
  {
    name: "Forget",
    singer: "The Tech Thieves",
    genre: "Electronic",
    audio: "./music/The_Tech_Thieves–Forget.mp3",
    album_img: "./images/forget_cover.jpg",
    id: 20,
  },
];
